GET http://localhost:5000

###
GET http://localhost:5000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRpdCBBa2JhcnMyIiwiZW1haWwiOiJhZGl0MkBnbWFpbC5jb20iLCJpYXQiOjE3MDI4MzEyNzAsImV4cCI6MTcwMjgzMTQ1MH0.KXeb4_44Tuzniyfef5AZ6IdTiEs2N7eKmxltuOJ1_UM

###
GET http://localhost:5000/users/c881f805-3199-44c0-b8d2-40ff6e73edde
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwibmFtZSI6IkFkaXQgQWtiYXJzIiwiZW1haWwiOiJhZGl0QGdtYWlsLmNvbSIsImlhdCI6MTcwMjU1MzI4OCwiZXhwIjoxNzAyNTUzNTg4fQ.Br0zR9dqqgWlvnsXIHzw0ur5FSE5gOF4HCj9JJWvap0

###
POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "Adit Akbars",
    "email": "adit@gmail.com",
    "password": "123454321",
    "confPassword": "123454321"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "adit2@gmail.com",
    "password": "123454321"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout

###
PUT http://localhost:5000/profile/c881f805-3199-44c0-b8d2-40ff6e73edde
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwibmFtZSI6IkFkaXQgQWtiYXJzIiwiZW1haWwiOiJhZGl0QGdtYWlsLmNvbSIsImlhdCI6MTcwMjE5OTczMCwiZXhwIjoxNzAyMjAwMDMwfQ.C-5P3wV6wsbKqsXs6VYZsZ8j2olJQj0BtKIcqvwihFc
Content-Type: application/json

{
    "photoUrl": "https://source.unsplash.com/100x100?twit",
    "birthDate": "1990-01-01",
    "age": 32,
    "gender": 1,      
    "weight": 70.5,
    "height": 175.0,
    "activity": 2,    
    "goal": 1       
}

###
PUT http://localhost:5000/profile/c881f805-3199-44c0-b8d2-40ff6e73edde/edit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwibmFtZSI6IkFkaXQgQWtiYXJzIiwiZW1haWwiOiJhZGl0QGdtYWlsLmNvbSIsImlhdCI6MTcwMjU1MzI4OCwiZXhwIjoxNzAyNTUzNTg4fQ.Br0zR9dqqgWlvnsXIHzw0ur5FSE5gOF4HCj9JJWvap0
Content-Type: application/json

{
    "photoUrl": "https://source.unsplash.com/100x100?zombie",
    "birthDate": "2000-01-01"     
}

###
POST http://localhost:5000/users/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRpdCBBa2JhcnMyIiwiZW1haWwiOiJhZGl0MkBnbWFpbC5jb20iLCJpYXQiOjE3MDMwODMyMzAsImV4cCI6MTcxODYzNTIzMH0.-q4kYMP2wbYNB7a5Xi4U2hldAjqx7nBj5k-CBsMu5kE
Content-Type: application/json

{
    "userId": "2"
}

###
POST http://localhost:5000/scan
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRpdCBBa2JhcnMyIiwiZW1haWwiOiJhZGl0MkBnbWFpbC5jb20iLCJpYXQiOjE3MDMwODExMTcsImV4cCI6MTcxODYzMzExN30.-cj_PxhdTqXmVdCajNfFa8ki-BTcW6m1hziEgEaiGH0

{
    "userId": "1",
    "nameFood": "fixing format timezone",
    "eatTime": "Dinner",
    "calorie": 303,
    "portion": 1,
    "total": 300
}

###
POST  http://localhost:5000/scanHistory
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRpdCBBa2JhcnMyIiwiZW1haWwiOiJhZGl0MkBnbWFpbC5jb20iLCJpYXQiOjE3MDMwODExMTcsImV4cCI6MTcxODYzMzExN30.-cj_PxhdTqXmVdCajNfFa8ki-BTcW6m1hziEgEaiGH0

{
    "userId": "1",
    "date": "2023-12-20"
}

###
POST  http://localhost:5000/scanHistory/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRpdCBBa2JhcnMyIiwiZW1haWwiOiJhZGl0MkBnbWFpbC5jb20iLCJpYXQiOjE3MDMwODExMTcsImV4cCI6MTcxODYzMzExN30.-cj_PxhdTqXmVdCajNfFa8ki-BTcW6m1hziEgEaiGH0

{
    "historyId": "b599042b-2533-42fa-b615-d64ce8ca8cdb"
}